FROM ghcr.io/nmfs-opensci/container-images/py-rocket-base:4.4-3.10

RUN pip install --upgrade --no-deps --force-reinstall --no-cache-dir git+https://github.com/jupyterhub/jupyter-rsession-proxy@8126737fffaa8af1dfffa3361d72982a4e6bb03c
