FROM ghcr.io/nmfs-opensci/container-images/py-rocket-base:4.4-3.10

RUN pip install --no-cache-dir git+https://github.com/jupyterhub/jupyter-rsession-proxy@pip install git+https://github.com/jupyterhub/jupyter-rsession-proxy@8126737fffaa8af1dfffa3361d72982a4e6bb03c
